import { ArrowRight, ArrowUpRight, Building2, CheckCircle2, Globe2, Home, Languages, Map, Route, ShieldCheck, Stethoscope } from "lucide-react";
import { australiaPathway, australiaSources } from "../data/australiaPathway";
import { assetPath } from "../lib/assetPath";

const icons = { language: Languages, building: Building2, route: Route, map: Map, home: Home };

function SectionHeading({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) {
  return <div className="max-w-3xl"><div className="eyebrow">{eyebrow}</div><h2 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">{title}</h2>{body && <p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p>}</div>;
}

function SourceLink({ label, url }: { label: string; url: string }) {
  return <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">{label} <ArrowUpRight size={13} /></a>;
}

export default function AustraliaPathway() {
  return <div className="space-y-10">
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
      <div className="grid lg:grid-cols-[1.05fr_0.95fr]">
        <div className="relative min-h-[350px] overflow-hidden bg-[#153c4a]">
          <img src={assetPath("/assets/australia/australia-guide.jpg")} alt="Australian landscape used for the Australia medical guide" className="absolute inset-0 h-full w-full object-cover" loading="eager" />
          <div className="absolute inset-0 bg-gradient-to-tr from-[#0b2b38]/95 via-[#123f52]/35 to-[#d9a441]/35" />
          <div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><div className="text-xs font-extrabold uppercase tracking-[0.22em] text-white/75">Australia guide for IMGs</div><h2 className="mt-2 max-w-xl text-3xl font-extrabold tracking-tight sm:text-4xl">A practical route to medical training in Australia.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/85">A calm overview of English evidence, AMC assessment, Ahpra registration, supervised practice, specialty training, and major teaching hospitals.</p></div>
        </div>
        <div className="flex flex-col justify-center p-6 sm:p-8"><div className="eyebrow">Guide / contents</div><h2 className="mt-2 text-xl font-extrabold">What is on this page?</h2><nav className="mt-4 grid gap-2 text-sm" aria-label="Australia guide contents">{[["why-australia", "Why choose Australia?"], ["requirements-australia", "IMG requirements"], ["pathway-australia", "Pathway and registration"], ["specialties-australia", "Specialty training"], ["tradeoffs-australia", "Advantages and disadvantages"], ["hospitals-australia", "Nine important hospitals"], ["sources-australia", "Official sources"]].map(([href, label]) => <a key={href} href={`#${href}`} className="flex items-center justify-between rounded-lg border border-border bg-background px-3 py-2.5 font-bold hover:border-primary/40 hover:bg-secondary/50"><span>{label}</span><ArrowRight size={14} className="text-primary" /></a>)}</nav></div>
      </div>
      <div className="grid gap-4 border-t border-border bg-secondary/30 p-4 sm:grid-cols-[1fr_1.25fr] sm:p-5"><div className="overflow-hidden rounded-xl border border-border bg-card"><img src={assetPath("/assets/media/country-australia_4dbe3131.jpg")} alt="Sydney Harbour and the Opera House in Australia" className="h-40 w-full object-cover" /></div><div className="rounded-xl border border-border bg-card p-5"><p className="eyebrow">Australia at a glance</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Australia’s IMG journey combines national registration standards with hospital and state-level recruitment. The right route depends on your qualification, internship, experience, and intended specialty.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-secondary px-3 py-1.5">AMC / Ahpra</span><span className="rounded-full bg-secondary px-3 py-1.5">English evidence</span><span className="rounded-full bg-secondary px-3 py-1.5">Supervised practice</span><span className="rounded-full bg-secondary px-3 py-1.5">College pathways</span></div></div></div>
    </section>

    <section id="why-australia"><SectionHeading eyebrow="01 / Why choose Australia?" title="Five reasons IMGs look toward Australia" body="Australia is not a single guaranteed checklist. Its appeal comes from the quality of the health system, the English-speaking environment, and multiple routes into supervised clinical work." /><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{australiaPathway.reasons.map((reason, index) => { const Icon = icons[reason.icon as keyof typeof icons]; return <article key={reason.title} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><Icon size={19} /></div><div className="mt-4 text-xs font-bold text-primary">0{index + 1}</div><h3 className="mt-1 text-base font-extrabold leading-5">{reason.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{reason.body}</p></article>; })}</div></section>

    <section id="requirements-australia"><SectionHeading eyebrow="02 / IMG requirements" title="The requirements to prepare" body="Use this as a planning framework, not a universal checklist. Confirm the current rules with the Medical Board of Australia, Ahpra, the AMC, and the relevant specialty college." /><div className="mt-5 grid gap-5 lg:grid-cols-3">{australiaPathway.requirements.map((item, index) => <article key={item.title} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-secondary text-primary"><ShieldCheck size={19} /></div><div><div className="text-xs font-bold text-primary">0{index + 1}</div><h3 className="mt-1 text-lg font-extrabold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.body}</p></div></div></article>)}</div><div className="mt-6 rounded-2xl border border-[#e5c992] bg-[#fffaf0] p-6 shadow-sm"><p className="text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Important distinction:</strong> immigration status, employment, and medical registration are separate. A visa does not replace registration, and a medical credential does not automatically create permission to work.</p></div></section>

    <section id="pathway-australia"><SectionHeading eyebrow="03 / Pathway and registration" title="From medical degree to supervised practice" body="The sequence below can overlap, but it helps prevent expensive mistakes. Your route may be shorter or longer depending on the authority, your prior training, and the position you secure." /><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_0.82fr]"><div className="space-y-4">{australiaPathway.stages.map(stage => <article key={stage.number} className="route-step rounded-2xl border border-border bg-card p-5 pl-14 shadow-sm sm:p-6 sm:pl-16"><span className="step-dot !top-6 !left-5">{stage.number}</span><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-extrabold">{stage.title}</h3><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-primary">{stage.timeframe}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{stage.body}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{stage.actions.map(action => <div key={action} className="rounded-lg bg-secondary/60 p-3 text-xs leading-5"><CheckCircle2 size={14} className="mb-1 text-primary" />{action}</div>)}</div><div className="mt-4 flex items-start gap-2 rounded-lg border border-primary/15 bg-primary/5 p-3 text-xs leading-5"><ArrowRight size={14} className="mt-0.5 shrink-0 text-primary" /><span><span className="font-bold">Checkpoint:</span> {stage.checkpoint}</span></div></article>)}</div><aside className="h-fit rounded-2xl border border-border bg-[#123f52] p-6 text-white shadow-lg lg:sticky lg:top-24"><div className="eyebrow !text-[#8bd3dc]">Keep this in view</div><h3 className="mt-2 text-xl font-extrabold">Registration is a staged process</h3><p className="mt-3 text-sm leading-6 text-white/75">Do not treat one exam, one job offer, or one visa as the whole route. Keep the registration authority, employer, specialty college, and immigration requirements aligned.</p><div className="mt-5 space-y-3">{["Check the current Medical Board standard", "Confirm the supervision plan", "Track deadlines and document validity"].map(item => <div key={item} className="flex items-start gap-2 text-xs leading-5 text-white/90"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-[#8bd3dc]" />{item}</div>)}</div></aside></div></section>

    <section id="specialties-australia"><SectionHeading eyebrow="04 / Specialty training" title="Getting into Australia is different from getting your specialty" body="Specialty selection is competitive and varies by college, state, hospital, experience, references, and annual recruitment needs." /><div className="mt-5 grid gap-4 md:grid-cols-3">{australiaPathway.specialtyNotes.map(([title, body]) => <article key={title} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2 text-primary"><Stethoscope size={18} /><span className="text-xs font-bold uppercase tracking-wider">Australia / IMG</span></div><h3 className="mt-4 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div></section>

    <section id="tradeoffs-australia"><SectionHeading eyebrow="05 / Trade-offs" title="The advantages and disadvantages of Australia" body="Australia can be an excellent destination for some IMGs, but the route is competitive and should be planned with current official requirements rather than broad promises." /><div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-[#b8dcca] bg-[#f5fbf7] p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8f0e1] text-[#197044]"><CheckCircle2 size={20} /></div><h3 className="text-xl font-extrabold text-[#164e35]">Advantages</h3></div><ul className="mt-5 space-y-3">{australiaPathway.advantages.map(item => <li key={item} className="flex items-start gap-2.5 text-sm leading-6"><CheckCircle2 size={16} className="mt-1 shrink-0 text-[#197044]" />{item}</li>)}</ul></article><article className="rounded-2xl border border-[#e5c6b8] bg-[#fff8f5] p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#f7dfd5] text-[#a34d2f]"><ShieldCheck size={20} /></div><h3 className="text-xl font-extrabold text-[#71331f]">Disadvantages</h3></div><ul className="mt-5 space-y-3">{australiaPathway.disadvantages.map(item => <li key={item} className="flex items-start gap-2.5 text-sm leading-6"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#a34d2f]" />{item}</li>)}</ul></article></div></section>

    <section id="hospitals-australia"><SectionHeading eyebrow="06 / Hospitals" title="Nine important Australian teaching hospitals" body="These are prominent teaching and tertiary centres, not a ranking or a promise of IMG recruitment. Check current vacancies, training accreditation, and eligibility rules before applying." /><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{australiaPathway.hospitals.map((hospital, index) => <article key={hospital.name} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="relative h-44 overflow-hidden bg-secondary"><img src={assetPath(hospital.image)} alt={`${hospital.name} exterior`} loading="lazy" className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-black/70 to-transparent p-4 pt-12 text-white"><p className="text-xs font-bold uppercase tracking-wider text-white/85">{hospital.city} · {hospital.state}</p><span className="text-xs font-bold text-white/80">0{index + 1}</span></div></div><div className="p-5"><div className="flex items-start gap-2"><Building2 size={18} className="mt-0.5 shrink-0 text-primary" /><h3 className="text-base font-extrabold leading-5">{hospital.name}</h3></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{hospital.body}</p><a href={hospital.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-bold text-primary hover:underline">Official site <ArrowUpRight size={13} /></a><p className="mt-3 text-[11px] leading-4 text-muted-foreground">Photo: {hospital.photoCredit}</p></div></article>)}</div></section>

    <section id="sources-australia" className="rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><Globe2 className="mt-1 shrink-0 text-primary" size={22} /><div><h2 className="text-xl font-extrabold">Verify before you spend money</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Rules, exam formats, fees, salaries, and recruitment priorities change. Start with the official sources below and confirm the exact requirements for your situation.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3">{australiaSources.map(([label, url]) => <SourceLink key={label} label={label} url={url} />)}</div><p className="mt-6 text-xs leading-5 text-muted-foreground">This guide is educational orientation, not medical, immigration, employment, or legal advice.</p></div></div></section>
  </div>;
}
