import { ArrowRight, ArrowUpRight, CheckCircle2, Globe2, Hospital, Languages, ShieldCheck, WalletCards } from "lucide-react";
import { irelandPathway } from "../data/irelandPathway";
import { assetPath } from "../lib/assetPath";

function SectionHeading({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) {
  return <div className="max-w-3xl"><div className="eyebrow">{eyebrow}</div><h2 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">{title}</h2>{body && <p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p>}</div>;
}
function IconBox({ children }: { children: React.ReactNode }) { return <div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-secondary text-primary">{children}</div>; }
function SourceLink({ label, url }: { label: string; url: string }) { return <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">{label}<ArrowUpRight size={13} /></a>; }

export default function IrelandPathway() {
  return <div className="space-y-10">
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
      <div className="grid lg:grid-cols-[1.05fr_0.95fr]">
        <div className="relative min-h-[350px] overflow-hidden bg-[#123d4a]"><img src={assetPath("/assets/ireland/ireland-guide-hero.jpg")} alt="Irish flag above a historic building" className="absolute inset-0 h-full w-full object-cover object-center opacity-80" /><div className="absolute inset-0 bg-gradient-to-tr from-[#092b39]/95 via-[#123d4a]/35 to-[#4d9b86]/55" /><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><div className="text-xs font-extrabold uppercase tracking-[0.22em] text-white/75">Ireland guide for IMGs</div><h2 className="mt-2 max-w-xl text-3xl font-extrabold tracking-tight sm:text-4xl">A clear route from medical school to specialist practice in Ireland.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/85">A practical guide to Medical Council registration, hospital employment, specialist training, immigration, salaries, and the Trauma & Orthopaedic pathway.</p></div></div>
        <div className="flex flex-col justify-center p-6 sm:p-8"><div className="eyebrow">Guide / contents</div><h2 className="mt-2 text-xl font-extrabold">What is on this page?</h2><nav className="mt-4 grid gap-2 text-sm" aria-label="Ireland guide contents">{[["why-ireland","Why Ireland?"],["requirements-ireland","Requirements"],["pathway-ireland","Step-by-step pathway"],["life-ireland","Salaries and work life"],["visas-ireland","Immigration"],["tradeoffs-ireland","Advantages and challenges"],["hospitals-ireland","Teaching hospitals"]].map(([href,label])=><a key={href} href={`#${href}`} className="flex items-center justify-between rounded-lg border border-border bg-background px-3 py-2.5 font-bold hover:border-primary/40 hover:bg-secondary/50"><span>{label}</span><ArrowRight size={14} className="text-primary" /></a>)}</nav></div>
      </div>
      <div className="grid gap-4 border-t border-border bg-secondary/30 p-4 sm:grid-cols-[1fr_1.25fr] sm:p-5"><div className="overflow-hidden rounded-xl border border-border bg-card"><img src={assetPath("/assets/media/country-ireland_e1ece753.jpg")} alt="Ireland visual" className="h-40 w-full object-cover" /></div><div className="rounded-xl border border-border bg-card p-5"><p className="eyebrow">Ireland at a glance</p><p className="mt-2 text-sm leading-6 text-muted-foreground">An English-speaking European system where IMGs usually move from Medical Council registration into salaried hospital work and then competitive specialist training.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-secondary px-3 py-1.5">IMG route</span><span className="rounded-full bg-secondary px-3 py-1.5">IELTS / OET</span><span className="rounded-full bg-secondary px-3 py-1.5">IMC</span><span className="rounded-full bg-secondary px-3 py-1.5">RCSI</span></div></div></div>
    </section>

    <section id="why-ireland"><SectionHeading eyebrow="01 / Why choose Ireland?" title="Six reasons IMGs consider Ireland" /><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{irelandPathway.reasons.map((reason, i)=><article key={reason.title} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><IconBox>{[<Languages size={19}/>,<Globe2 size={19}/>,<ShieldCheck size={19}/>,<Hospital size={19}/>,<WalletCards size={19}/>,<Globe2 size={19}/>][i]}</IconBox><h3 className="mt-4 text-base font-extrabold">{reason.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{reason.body}</p></article>)}</div></section>

    <section id="requirements-ireland"><SectionHeading eyebrow="02 / Requirements" title="The requirements to prepare" body="Use this as a planning framework. Registration rules, accepted evidence, and examinations can change, so verify every item with the current Medical Council and training-body guidance." /><div className="mt-5 grid gap-5 lg:grid-cols-3">{irelandPathway.requirements.map(group=><article key={group.title} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start gap-4"><IconBox><CheckCircle2 size={19}/></IconBox><div><h3 className="text-lg font-extrabold">{group.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{group.body}</p></div></div><div className="mt-5 space-y-3 border-t border-border pt-5">{group.items.map(item=><div key={item} className="flex items-start gap-2.5 text-sm leading-6"><CheckCircle2 size={15} className="mt-1 shrink-0 text-primary" />{item}</div>)}</div></article>)}</div><div className="mt-6 rounded-2xl border border-[#e5c992] bg-[#fffaf0] p-6 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Sudanese IMG note:</strong> qualifying Sudanese internship training may support a PRES exemption, but this is not automatic registration. The Medical Council still assesses qualifications, documents, English evidence, and the individual route.</div></section>

    <section id="pathway-ireland"><SectionHeading eyebrow="03 / Step-by-step pathway" title="From medical school to specialist registration" body="The sequence below focuses on the Irish IMG route and the additional steps for someone targeting Trauma & Orthopaedic Surgery." /><div className="mt-6 space-y-4">{irelandPathway.stages.map(stage=><article key={stage.number} className="route-step rounded-2xl border border-border bg-card p-5 pl-14 shadow-sm sm:p-6 sm:pl-16"><span className="step-dot !top-6 !left-5">{stage.number}</span><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-extrabold">{stage.title}</h3><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-primary">{stage.timeframe}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{stage.body}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{stage.actions.map(action=><div key={action} className="rounded-lg bg-secondary/60 p-3 text-xs leading-5"><CheckCircle2 size={14} className="mb-1 text-primary" />{action}</div>)}</div><div className="mt-4 flex items-start gap-2 rounded-lg border border-primary/15 bg-primary/5 p-3 text-xs leading-5"><ArrowRight size={14} className="mt-0.5 shrink-0 text-primary" /><span><b>Checkpoint:</b> {stage.checkpoint}</span></div></article>)}</div></section>

    <section id="life-ireland"><SectionHeading eyebrow="04 / Salaries and work–life balance" title="Salaries, workload, and realistic expectations" body="These are 2026 HSE basic annual salary figures. Overtime, night duty, on-call, allowances, tax, and living costs can change the final picture." /><div className="mt-5 overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-secondary/70 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-4 font-extrabold">Role</th><th className="px-5 py-4 font-extrabold">Basic annual salary</th><th className="px-5 py-4 font-extrabold">Context</th></tr></thead><tbody>{irelandPathway.salaryBands.map(band=><tr key={band.role} className="border-t border-border align-top"><td className="px-5 py-4 font-extrabold">{band.role}</td><td className="px-5 py-4 font-bold text-primary">{band.annual}</td><td className="px-5 py-4 leading-6 text-muted-foreground">{band.note}</td></tr>)}</tbody></table></div></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-[#b8dccf] bg-[#f3fbf7] p-6"><h3 className="text-base font-extrabold">Work–life balance</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Ireland can offer structured contracts, annual leave, public holidays, and defined additional-payment rules. It is not a low-intensity residency: specialty, hospital, roster, nights, and emergency workload matter.</p></article><article className="rounded-2xl border border-[#e8c3c5] bg-[#fff7f7] p-6"><h3 className="text-base font-extrabold">The competitive reality</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Getting an Irish hospital job is not the same as entering formal specialist training. You may need time in non-training work before becoming competitive for CST, BST, or HST.</p></article></div></section>

    <section id="visas-ireland"><SectionHeading eyebrow="05 / Immigration" title="Plan permission alongside registration" body="Non-EEA doctors need the correct employment permission and, where required, an Irish visa. Immigration status can also affect training eligibility and allocation." /><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Employment permit","A qualifying job and appropriate permission are normally needed before working."],["Stamp 1H","A relevant permission for doctors working as NCHDs under the applicable employment permit."],["PRES travel","A short-stay exam visa does not itself allow a doctor to remain and start work after PRES."]].map(([title,body])=><article key={title} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h3 className="font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div></section>

    <section id="tradeoffs-ireland"><SectionHeading eyebrow="06 / Advantages and challenges" title="Is Ireland a good choice for an IMG?" /><div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-[#b8dccf] bg-[#f3fbf7] p-6"><h3 className="text-lg font-extrabold">Strong reasons</h3><ul className="mt-4 space-y-3 text-sm leading-6">{["English-speaking healthcare system", "Potential recognition advantage for a qualifying Sudanese internship", "Salaried hospital and training posts", "Clear RCSI surgical pathway", "European location and international workforce"].map(item=><li key={item} className="flex items-start gap-2"><CheckCircle2 size={15} className="mt-1 shrink-0 text-[#267a5b]" />{item}</li>)}</ul></article><article className="rounded-2xl border border-[#e8c3c5] bg-[#fff7f7] p-6"><h3 className="text-lg font-extrabold">Important challenges</h3><ul className="mt-4 space-y-3 text-sm leading-6">{["Specialist training is competitive", "Housing, especially in Dublin, can be expensive", "Non-training jobs may extend the timeline", "Immigration status and eligibility rules matter", "Taxes and living costs reduce take-home pay"].map(item=><li key={item} className="flex items-start gap-2"><ShieldCheck size={15} className="mt-1 shrink-0 text-[#a52b3b]" />{item}</li>)}</ul></article></div></section>

    <section id="hospitals-ireland"><SectionHeading eyebrow="07 / Teaching hospitals" title="Nine important hospitals to research" body="These major teaching and Model 4 hospital sites are useful starting points when researching jobs, rotations, and surgical exposure." /><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{irelandPathway.hospitals.map((hospital, i)=><article key={hospital.name} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><img src={assetPath(hospital.image)} alt={`${hospital.name}, ${hospital.location}`} className="h-44 w-full object-cover" loading="lazy" /><div className="p-4"><div className="text-xs font-extrabold uppercase tracking-wider text-primary">{String(i + 1).padStart(2, "0")} · {hospital.location}</div><h3 className="mt-1 text-base font-extrabold">{hospital.name}</h3><a href={hospital.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-[11px] leading-4 text-muted-foreground hover:text-primary hover:underline">Photo: {hospital.source}</a></div></article>)}</div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2">{irelandPathway.sources.map(([label,url])=><SourceLink key={label} label={label} url={url} />)}</div><p className="mt-5 rounded-lg bg-secondary/60 p-3 text-xs leading-5 text-muted-foreground">For education only. Requirements, salaries, immigration rules, and programme criteria can change. Verify current details with the official authority and training programme before making decisions.</p></section>
  </div>;
}
